DPNG-6255 kubernetes integration
Added pushing demiurge and kubernetes-broker; changed fetcher for getting demiurge's envs

Vars for demiurge are now without unneeded artifacts

Added vars: username, password for demiurge

include_groups feature

Improved include_Groups invocation

fixed tests - include_groups added

Added multi-group feature, code cleanup, fixed envs for demiurge

Fixed AttributeError: 'list' object has no attribute 'split'

Added security_groups to appstack

Fix for security-groups

Fixed converting dict-object-dict

Fixed pylint issues, code cleanup

Fixed pylint issues

Pylint fixes

Added missing docstring

Coverage up

Added groups and kubernetes to the readme